templates:
  new_order_owner:
    format: |
      ğŸ’¸ New order alert!
      ğŸ•“ Time: {time}
      ğŸ“… Date: {date}
      ğŸ’° Total: {total}
      ğŸ™â€â™‚ï¸ Client: {client}
      ğŸŒ IP: {ip}
  
  new_affiliate_owner:
    format: |
      ğŸ™â€â™‚ï¸ New affiliate alert!
      ğŸ•“ Time: {time}
      ğŸ“… Date: {date}
      ğŸ“ Phone number: {phone}
      ğŸ—ï¸ Affiliate token: {token}
  
  affiliate_registration_success:
    format: "Inscription confirmÃ©e - Votre lien affiliÃ©: {link}?{token}"
  
  affiliate_already_registered:
    format: "Vous Ãªtes dÃ©jÃ  enregistrÃ© - Votre lien affiliÃ©: {link}?{token}"
  
  new_order_affiliate:
    format: |
      ğŸ’¸ Nouvelle commande !
      ğŸ•“ Heure: {time}
      ğŸ“… Date: {date}
      ğŸ’° Total: {total}
      ğŸ™â€â™‚ï¸ Client: {client}
      ğŸŒ IP: {ip}
  
  system_alert:
    format: "ğŸš¨ SYSTEM ALERT: {message}"
  
  webhook_alert:
    format: "âš ï¸ WEBHOOK ALERT: {message}"
